(define (problem pddl-problem)
 (:domain pddl-domain)
 (:objects
   duck apple cerealbox cardboardbox orange glass longglass board - item
   orange_bin blue_bin purple_bin green_bin - bin
   robot_0 - robot
 )
 (:init (= (duration_ duck orange_bin) 18) (= (duration_ board orange_bin) 15) (= (duration_ cardboardbox blue_bin) 11) (= (duration_ cerealbox blue_bin) 12) (= (duration_ apple green_bin) 14) (= (duration_ orange green_bin) 14) (= (duration_ longglass purple_bin) 12) (= (duration_ glass purple_bin) 9) (destination duck orange_bin) (destination board orange_bin) (destination cardboardbox blue_bin) (destination cerealbox blue_bin) (destination apple green_bin) (destination orange green_bin) (destination longglass purple_bin) (destination glass purple_bin) (= (reward duck orange_bin) 10) (= (reward board orange_bin) 90) (= (reward cardboardbox blue_bin) 12) (= (reward cerealbox blue_bin) 33) (= (reward apple green_bin) 1) (= (reward orange green_bin) 2) (= (reward longglass purple_bin) 32) (= (reward glass purple_bin) 27) (robot_at_item robot_0 duck) (= (timeremaining) 20000) (robot_empty robot_0) (= (reward apple orange_bin) 0) (= (reward cerealbox orange_bin) 0) (= (reward cardboardbox orange_bin) 0) (= (reward orange orange_bin) 0) (= (reward glass orange_bin) 0) (= (reward longglass orange_bin) 0) (= (reward duck blue_bin) 0) (= (reward apple blue_bin) 0) (= (reward orange blue_bin) 0) (= (reward glass blue_bin) 0) (= (reward longglass blue_bin) 0) (= (reward board blue_bin) 0) (= (reward duck purple_bin) 0) (= (reward apple purple_bin) 0) (= (reward cerealbox purple_bin) 0) (= (reward cardboardbox purple_bin) 0) (= (reward orange purple_bin) 0) (= (reward board purple_bin) 0) (= (reward duck green_bin) 0) (= (reward cerealbox green_bin) 0) (= (reward cardboardbox green_bin) 0) (= (reward glass green_bin) 0) (= (reward longglass green_bin) 0) (= (reward board green_bin) 0) (= (reward_robot) 0) (= (duration_ apple orange_bin) 100) (= (duration_ cerealbox orange_bin) 100) (= (duration_ cardboardbox orange_bin) 100) (= (duration_ orange orange_bin) 100) (= (duration_ glass orange_bin) 100) (= (duration_ longglass orange_bin) 100) (= (duration_ duck blue_bin) 100) (= (duration_ apple blue_bin) 100) (= (duration_ orange blue_bin) 100) (= (duration_ glass blue_bin) 100) (= (duration_ longglass blue_bin) 100) (= (duration_ board blue_bin) 100) (= (duration_ duck purple_bin) 100) (= (duration_ apple purple_bin) 100) (= (duration_ cerealbox purple_bin) 100) (= (duration_ cardboardbox purple_bin) 100) (= (duration_ orange purple_bin) 100) (= (duration_ board purple_bin) 100) (= (duration_ duck green_bin) 100) (= (duration_ cerealbox green_bin) 100) (= (duration_ cardboardbox green_bin) 100) (= (duration_ glass green_bin) 100) (= (duration_ longglass green_bin) 100) (= (duration_ board green_bin) 100))
 (:goal (and (inbin duck orange_bin)))
)
